[project]
name = "stackslotto"
description = "On-Chain Lottery System for Stacks"
authors = ["Bamzz"]
telemetry = false
cache_dir = ".cache"
requirements = []

[contracts.stacks-lotto]
path = "contracts/stacks-lotto.clar"
clarity_version = 2
epoch = 2.5
